# Generated by Django 3.1.3 on 2021-02-17 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import slayer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('creators', models.ManyToManyField(related_name='contests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('statement', models.FileField(upload_to=slayer.models.problem_file_name)),
                ('time_limit', models.PositiveIntegerField()),
                ('test_case_input', models.FileField(upload_to=slayer.models.problem_file_name)),
                ('test_case_output', models.FileField(upload_to=slayer.models.problem_file_name)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slayer.contest')),
                ('creators', models.ManyToManyField(related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python 3', 'Python 3')], max_length=200)),
                ('code', models.FileField(upload_to=slayer.models.submission_file_name)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slayer.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionVerdict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slayer.submission')),
            ],
        ),
    ]
