# Generated by Django 3.1.3 on 2021-02-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python 3', 'Python 3')], default='Python 3', max_length=200),
        ),
    ]
